# -*- coding: utf-8 -*-
"""Aml lab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RmGsAsplN-gE84CABDVs2JZcdzjuZgPn
"""

!pip install xlrd

from google.colab import files

uploaded = files.upload()

import zipfile

zip_file = "Student grade Prediction.zip"

with zipfile.ZipFile(zip_file, 'r') as zip_ref:
    zip_ref.extractall()

print("Files extracted successfully!")

import pandas as pd

df = pd.read_excel(
    "Student grade Prediction/cgpaPRED.xls",
    engine="xlrd"
)

df.head()

print(df.columns.tolist())

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import pandas as pd

df = pd.read_excel("Student grade Prediction/cgpaPRED.xls")

df.head()

df.info()

df.isnull().sum()

import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))

df.boxplot(column=['SEM 1', 'SEM 2', 'SEM 3', 'SEM 4', 'SEM 5'])

plt.title("Box Plot of Semester CGPAs")
plt.xlabel("Semester")
plt.ylabel("CGPA")

plt.show()

df.describe()

import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))

corr = df.corr()

plt.imshow(corr, cmap='coolwarm')

plt.colorbar()

plt.xticks(range(len(corr.columns)), corr.columns, rotation=45)

plt.yticks(range(len(corr.columns)), corr.columns)

plt.title("Correlation Matrix")

plt.show()

X = df[['SEM 4']]

y = df['SEM 5']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

slr = LinearRegression()

slr.fit(X_train, y_train)

X_test_for_slr = pd.DataFrame(X_test['SEM 4'])
y_pred = slr.predict(X_test_for_slr)

print("Simple Linear Regression")

print("Intercept :", slr.intercept_)

print("Coefficient :", slr.coef_[0])

print("MAE :", mean_absolute_error(y_test, y_pred))

print("RMSE :", np.sqrt(mean_squared_error(y_test, y_pred)))

print("R2 Score :", r2_score(y_test, y_pred))

plt.figure(figsize=(7,5))

plt.scatter(X_test, y_test)

plt.plot(X_test, y_pred, color='red')

plt.xlabel("SEM 4")

plt.ylabel("SEM 5")

plt.title("Simple Linear Regression")

plt.show()

X = df[['SEM 1', 'SEM 2', 'SEM 3', 'SEM 4']]

y = df['SEM 5']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

mlr = LinearRegression()

mlr.fit(X_train, y_train)

pred = mlr.predict(X_test)

print("Multiple Linear Regression")

print("Intercept :", mlr.intercept_)

print("MAE :", mean_absolute_error(y_test, pred))

print("RMSE :", np.sqrt(mean_squared_error(y_test, pred)))

print("R2 Score :", r2_score(y_test, pred))

coef = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": mlr.coef_
})

coef

comparison = pd.DataFrame({
    "Actual": y_test,
    "Predicted": pred
})

comparison.head(15)

plt.figure(figsize=(7,5))

plt.scatter(y_test, pred)

plt.plot([min(y_test), max(y_test)],
         [min(y_test), max(y_test)],
         color='red')

plt.xlabel("Actual SEM 5")

plt.ylabel("Predicted SEM 5")

plt.title("Actual vs Predicted")

plt.show()

new_student = pd.DataFrame({
    "SEM 1":[7.5],
    "SEM 2":[7.8],
    "SEM 3":[8.0],
    "SEM 4":[8.3]
})

prediction = mlr.predict(new_student)

print("Predicted SEM 5 CGPA :", prediction[0])

slr_rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mlr_rmse = np.sqrt(mean_squared_error(y_test, pred))

results = pd.DataFrame({
    "Model": ["Simple Linear Regression", "Multiple Linear Regression"],
    "R2 Score": [
        r2_score(y_test, y_pred),
        r2_score(y_test, pred)
    ],
    "RMSE": [
        slr_rmse,
        mlr_rmse
    ]
})

print(results)